name: Ruby
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Latest Ruby
      run: sudo apt update && sudo apt install -y ruby-full
    - name: Check Ruby Version
      run: ruby -v
    - name: Install Bundler & Install RSpec
      run: sudo gem install bundler && sudo gem install rspec rspec
    - name: Running Bundle Install from Gemfile
      run: bundle install
    - name: Run Rspec Tests
      run: rspec ./spec
